[workers]
vm1 ansible_host=192.168.123.21 ansible_user=userver
vm2 ansible_host=192.168.123.22 ansible_user=userver
vm3 ansible_host=192.168.123.23 ansible_user=userver

[load-balancer]
vm0 ansible_host=192.168.123.20 ansible_user=userver