name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build --build-arg APP_COMMIT_MESSAGE="$(git log -1 --pretty=format:"%B")" --build-arg APP_COMMIT_HASH="$(git log -1 --pretty=format:"%H")" -t 1604071/simple-todo .

      - name: Push Docker Image
        run: docker push 1604071/simple-todo

  deploy:
    runs-on: self-hosted
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: checking directory
        run: |
          pwd
          ls

      - name: Run Ansible Playbook with Become Password
        run: |
          cd ansible/
          ansible-playbook \
            -i inventory.ini \
            playbook.yml \
            --extra-vars "ansible_become_password=${{ secrets.ANSIBLE_BECOME_PASS }}"
